/** @format */

useEffect(() => {
  cart.forEach((item) => {
    dispatch(updateCart({ userId, product: item, quantity: item.quantity }));
  });
}, [cart, userId, dispatch]);

const handleAddToCart = (product) => {
  handelcart(product);
};
const handelcart = (product) => {
  let updatedCart = [...cart];
  let productExists = false;

  updatedCart.forEach((item) => {
    if (item.asin === product.asin) {
      productExists = true;
      item.quantity += 1;
    }
  });

  if (!productExists) {
    product.quantity = 1;
    updatedCart = [...updatedCart, product];
  }
  cart = updatedCart;

  // Dispatch the updateCart action
  dispatch(updateCart({ userId, product, quantity: product.quantity }));
};

// function handelcart(arr) {
//   let tm = cart;
//   let val = false;

//   tm.forEach((element) => {
//     if (element.asin === arr.asin) {
//       val = true;
//       element.quantity = element.quantity + 1;
//     }
//   });
//   if (val === false) {
//     arr.quantity = 1;
//     setCart([...tm, arr]);
//   } else {
//     setCart(tm);
//   }
// }

function handellist(arr) {
  let tm = wishlist;
  let val = false;
  tm.forEach((element) => {
    if (element.asin === arr.asin) val = true;
  });
  if (val === false) setWishlist([...tm, arr]);
}

const handleAddToWishlist = () => {
  dispatch(updateWishlist({ userId, wishlist }));
};

[
  {
    asin: "B07ZZD6XL1",
    product_title:
      "Genteel Matic Liquid Detergent Refill Pouch for Top load Washing - 2kg | No Soda Formula | with Added Fabric Conditioner",
    product_price: "₹207",
    unit_price: "₹103.50",
    unit_count: 2,
    product_original_price: "₹290",
    currency: "INR",
    product_star_rating: "4.3",
    product_num_ratings: 13771,
    product_url: "https://www.amazon.in/dp/B07ZZD6XL1",
    product_photo:
      "https://m.media-amazon.com/images/I/61B304RHorL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹207",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "30K+ bought in past month",
    delivery: "Get it by Tomorrow, 6 JulyFREE Delivery by Amazon",
  },
  {
    asin: "B07XXFB9CZ",
    product_title:
      "Sfane Polyester 23cms Duffle/Shoulder/Gym Bag for Men &amp; Women with Separate Shoe Compartment (Grey)",
    product_price: "₹415",
    product_original_price: "₹1,149",
    currency: "INR",
    product_star_rating: "4.4",
    product_num_ratings: 10145,
    product_url: "https://www.amazon.in/dp/B07XXFB9CZ",
    product_photo:
      "https://m.media-amazon.com/images/I/71W80G89rwL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹415",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "3K+ bought in past month",
    delivery: "FREE Delivery by Amazon",
  },
  {
    asin: "B09C3VGV8G",
    product_title: "Surf Excel Easy Wash Detergent Powder - 5 Kg",
    product_price: "₹577",
    unit_price: "₹115.40",
    unit_count: 5,
    product_original_price: "₹770",
    currency: "INR",
    product_star_rating: "4.4",
    product_num_ratings: 16462,
    product_url: "https://www.amazon.in/dp/B09C3VGV8G",
    product_photo:
      "https://m.media-amazon.com/images/I/61IxGNC3xPL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 5,
    product_minimum_offer_price: "₹549",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "20K+ bought in past month",
    delivery: "Get it by Tomorrow, 6 JulyFREE Delivery by Amazon",
  },
  {
    asin: "B0BV6WSF33",
    product_title:
      "ANNI DESIGNER Women&#x27;s Cotton Blend Straight Printed Kurta &amp; Pant",
    product_price: "₹479",
    product_original_price: "₹2,599",
    currency: "INR",
    product_star_rating: "3.6",
    product_num_ratings: 7990,
    product_url: "https://www.amazon.in/dp/B0BV6WSF33",
    product_photo:
      "https://m.media-amazon.com/images/I/61q-JREtrAL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹479",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "400+ bought in past month",
    delivery: "FREE Delivery by Amazon",
  },
  {
    asin: "B0BYX3P5L8",
    product_title:
      "Gadget Deals Triple Combo - USB Light | USB Fan - Mini USB Bulb - Emergency Combo (use with Laptop, Phone, Desktop) USB Led Light | USB Fan (Multicolor)- USB Light and Fan",
    product_price: "₹169",
    product_original_price: "₹999",
    currency: "INR",
    product_star_rating: "3.5",
    product_num_ratings: 174,
    product_url: "https://www.amazon.in/dp/B0BYX3P5L8",
    product_photo:
      "https://m.media-amazon.com/images/I/31sugMOd9RL._AC_UL832_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹169",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: "Get it by Tomorrow, 6 JulyFREE Delivery by Amazon",
  },
  {
    asin: "B09N3K2ZCP",
    product_title:
      "Fargo Handbag For Women And Girls COMBO SET OF 5 (Light5pc)",
    product_price: "₹449",
    product_original_price: "₹2,999",
    currency: "INR",
    product_star_rating: "3.2",
    product_num_ratings: 4699,
    product_url: "https://www.amazon.in/dp/B09N3K2ZCP",
    product_photo:
      "https://m.media-amazon.com/images/I/51-+SFrhYFL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹449",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "300+ bought in past month",
    delivery: "FREE Delivery by Amazon",
  },
  {
    asin: "B07B7J7FFH",
    product_title:
      "AL FASCINO Wallets for men leather original purses for men RFID wallet for men leather wallet for men money purse for men Wallet Mens wallet men wallet gents wallets card holder for men gents wallets",
    product_price: "₹499",
    product_original_price: "₹2,999",
    currency: "INR",
    product_star_rating: "4.2",
    product_num_ratings: 11324,
    product_url: "https://www.amazon.in/dp/B07B7J7FFH",
    product_photo:
      "https://m.media-amazon.com/images/I/71smoRJEX+L._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹499",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "1K+ bought in past month",
    delivery: "FREE Delivery by Amazon",
  },
  {
    asin: "B00Z0NMFKU",
    product_title:
      "Fostelo Women&#x27;s Style Diva Faux Leather Handbag (Large)",
    product_price: "₹569",
    product_original_price: "₹2,799",
    currency: "INR",
    product_star_rating: "3.8",
    product_num_ratings: 10554,
    product_url: "https://www.amazon.in/dp/B00Z0NMFKU",
    product_photo:
      "https://m.media-amazon.com/images/I/61Fa7wW9FvL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹569",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "600+ bought in past month",
    delivery: "FREE Delivery by Amazon",
  },
  {
    asin: "B0BN41V435",
    product_title:
      "Wedani Women&#x27;s Casual Short sleeves Round Neck Foral Top",
    product_price: "₹216",
    product_original_price: "₹849",
    currency: "INR",
    product_star_rating: "3.2",
    product_num_ratings: 2155,
    product_url: "https://www.amazon.in/dp/B0BN41V435",
    product_photo:
      "https://m.media-amazon.com/images/I/81KKhwy4QoL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹216",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: "FREE Delivery by Amazon",
  },
  {
    asin: "B0BYDLYQ9T",
    product_title: "rytras Women&#x27;s Floral Printed Cotton Top",
    product_price: "₹479",
    product_original_price: "₹1,599",
    currency: "INR",
    product_star_rating: "4",
    product_num_ratings: 2198,
    product_url: "https://www.amazon.in/dp/B0BYDLYQ9T",
    product_photo:
      "https://m.media-amazon.com/images/I/713wEcCIKRL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹479",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "300+ bought in past month",
    delivery: "FREE Delivery by Amazon",
  },
  {
    asin: "B0BM4JCXXD",
    product_title:
      "Aahwan Women&#x27;s &amp; Girls&#x27; Solid Long Sleeve Slim Fit Top/T-Shirt",
    product_price: "₹369",
    product_original_price: "₹1,999",
    currency: "INR",
    product_star_rating: "3.6",
    product_num_ratings: 1626,
    product_url: "https://www.amazon.in/dp/B0BM4JCXXD",
    product_photo:
      "https://m.media-amazon.com/images/I/71MmrkYPkeL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹369",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "100+ bought in past month",
    delivery: "FREE Delivery by Amazon",
  },
  {
    asin: "B0BY2NM7C8",
    product_title:
      "Fire-Boltt Phoenix Ultra Luxury Stainless Steel, Bluetooth Calling Smartwatch, AI Voice Assistant, Metal Body with 120+ Sports Modes, SpO2, Heart Rate Monitoring (Multicolor)",
    product_price: "₹1,499",
    product_original_price: "₹12,499",
    currency: "INR",
    product_star_rating: "4.1",
    product_num_ratings: 64671,
    product_url: "https://www.amazon.in/dp/B0BY2NM7C8",
    product_photo:
      "https://m.media-amazon.com/images/I/71D7jU3tUUL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹1,499",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "2K+ bought in past month",
    delivery: "Get it by Tomorrow, 6 JulyFREE Delivery by Amazon",
  },
  {
    asin: "B08GY5DRXB",
    product_title:
      "Sunfeast YiPPee! Magic Masala, Instant Noodles 720G/810G/840 Grams (Pack Of 12) ( Weight May Vary )",
    product_price: "₹142",
    unit_price: "₹16.90",
    unit_count: 8,
    product_original_price: "₹168",
    currency: "INR",
    product_star_rating: "4.3",
    product_num_ratings: 13989,
    product_url: "https://www.amazon.in/dp/B08GY5DRXB",
    product_photo:
      "https://m.media-amazon.com/images/I/71W61ls0b8L._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹142",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "(₹16.90₹16.90/100 g)",
    delivery: "Get it by Tomorrow, 6 JulyFREE Delivery by Amazon",
  },
  {
    asin: "B0BN41RF4S",
    product_title: "Wedani Women&#x27;s Casual Puff sleeves V neck Foral Top",
    product_price: "₹179",
    product_original_price: "₹899",
    currency: "INR",
    product_star_rating: "3.1",
    product_num_ratings: 1352,
    product_url: "https://www.amazon.in/dp/B0BN41RF4S",
    product_photo:
      "https://m.media-amazon.com/images/I/712esb-T+hL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹179",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: "FREE Delivery by Amazon",
  },
  {
    asin: "B0B9YQ7NSF",
    product_title: "DHRUVI TRENDZ Women Regular Fit Rayon Shirt",
    product_price: "₹289",
    product_original_price: "₹1,999",
    currency: "INR",
    product_star_rating: "3.5",
    product_num_ratings: 658,
    product_url: "https://www.amazon.in/dp/B0B9YQ7NSF",
    product_photo:
      "https://m.media-amazon.com/images/I/71ii6I1DA0L._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹289",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: "FREE Delivery by Amazon",
  },
  {
    asin: "B09NNMWZ71",
    product_title:
      "Aahwan Women&#x27;s &amp; Girls&#x27; Solid Ribbed Square Neck Tank Tops",
    product_price: "₹299",
    product_original_price: "₹999",
    currency: "INR",
    product_star_rating: "3.7",
    product_num_ratings: 2804,
    product_url: "https://www.amazon.in/dp/B09NNMWZ71",
    product_photo:
      "https://m.media-amazon.com/images/I/615pREhXdPL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹299",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "300+ bought in past month",
    delivery: "FREE Delivery by Amazon",
  },
  {
    asin: "B08DRKZDHT",
    product_title: "Henko More Light Extra Power Detergent powder 4kg",
    product_price: "₹234",
    unit_price: "₹58.50",
    unit_count: 4,
    product_original_price: "₹525",
    currency: "INR",
    product_star_rating: "4.1",
    product_num_ratings: 19599,
    product_url: "https://www.amazon.in/dp/B08DRKZDHT",
    product_photo:
      "https://m.media-amazon.com/images/I/51J2SNCx0jL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹234",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "10K+ bought in past month",
    delivery: "Get it by Tomorrow, 6 JulyFREE Delivery by Amazon",
  },
  {
    asin: "B0BN3Z7BXN",
    product_title: "Wedani Women&#x27;s Casual Bell sleeves V-neck Foral Top",
    product_price: "₹385",
    product_original_price: "₹1,049",
    currency: "INR",
    product_star_rating: "3.3",
    product_num_ratings: 930,
    product_url: "https://www.amazon.in/dp/B0BN3Z7BXN",
    product_photo:
      "https://m.media-amazon.com/images/I/91d7va5ED8L._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹385",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: "FREE Delivery by Amazon",
  },
  {
    asin: "B09TP8XZBC",
    product_title:
      "Leriya Fashion Women&#x27;s Plus Size Short Sleeve Deep V Neck Self Belted Casual Peplum Wrap Blouse Top",
    product_price: "₹289",
    product_original_price: "₹1,999",
    currency: "INR",
    product_star_rating: "3.6",
    product_num_ratings: 1571,
    product_url: "https://www.amazon.in/dp/B09TP8XZBC",
    product_photo:
      "https://m.media-amazon.com/images/I/71b0A6T6FpL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹289",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: "FREE Delivery by Amazon",
  },
  {
    asin: "B0833VN251",
    product_title:
      "Yash Gallery Women&#x27;S Viscose Rayon Stripe Printed Straight Top for Women",
    product_price: "₹378",
    product_original_price: "₹1,999",
    currency: "INR",
    product_star_rating: "4",
    product_num_ratings: 731,
    product_url: "https://www.amazon.in/dp/B0833VN251",
    product_photo:
      "https://m.media-amazon.com/images/I/61eT2Zob2vL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹378",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: "FREE Delivery by Amazon",
  },
  {
    asin: "B08CSHBPD5",
    product_title:
      "L&#x27;Oreal Paris Shampoo, For Damaged and Weak Hair, With Pro-Keratin + Ceramide, Total Repair 5, 1ltr",
    product_price: "₹849",
    unit_price: "₹84.90",
    unit_count: 10,
    product_original_price: "₹1,099",
    currency: "INR",
    product_star_rating: "4.2",
    product_num_ratings: 38722,
    product_url: "https://www.amazon.in/dp/B08CSHBPD5",
    product_photo:
      "https://m.media-amazon.com/images/I/51eWbvvpYHL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 5,
    product_minimum_offer_price: "₹799",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "2K+ bought in past month",
    delivery: "Get it by Wednesday 10 July",
  },
  {
    asin: "B07F8D6QLL",
    product_title:
      "Surf Excel Matic Top Load Liquid Detergent 2 L Refill Pouch, Designed To Remove Tough Stains, For Top Load Washing Machines",
    product_price: "₹336",
    unit_price: "₹168",
    unit_count: 2,
    product_original_price: "₹390",
    currency: "INR",
    product_star_rating: "4.5",
    product_num_ratings: 49524,
    product_url: "https://www.amazon.in/dp/B07F8D6QLL",
    product_photo:
      "https://m.media-amazon.com/images/I/61k2Z60DINL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹336",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "7K+ bought in past month",
    delivery: "Get it by Tomorrow, 6 JulyFREE Delivery by Amazon",
  },
  {
    asin: "B09FQ8ZYQP",
    product_title:
      "OM SAI LATEST CREATION Women Striped Top with Full Sleeves for Office Wear, Casual Wear Western Top",
    product_price: "₹289",
    product_original_price: "₹1,999",
    currency: "INR",
    product_star_rating: "3.3",
    product_num_ratings: 1196,
    product_url: "https://www.amazon.in/dp/B09FQ8ZYQP",
    product_photo:
      "https://m.media-amazon.com/images/I/91c0pdWCUQL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹289",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: "FREE Delivery by Amazon",
  },
  {
    asin: "B0CDLX1NXB",
    product_title:
      "NAINVISH Tops for Women Printed Shirt Top for Women | Tops for Women Stylish Latest | Office Wear Tops for Women | Cotton Blend Tops for Women",
    product_price: "₹299",
    product_original_price: "₹4,599",
    currency: "INR",
    product_star_rating: "3.7",
    product_num_ratings: 284,
    product_url: "https://www.amazon.in/dp/B0CDLX1NXB",
    product_photo:
      "https://m.media-amazon.com/images/I/71JiVV7074L._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹299",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: "FREE Delivery by Amazon",
  },
  {
    asin: "B0CDLZBPZ6",
    product_title:
      "NAINVISH Tops for Women Printed Shirt Top for Women | Tops for Women Stylish Latest | Office Wear Tops for Women | Cotton Blend Tops for Women | Mandarin Collar Top",
    product_price: "₹299",
    product_original_price: "₹4,599",
    currency: "INR",
    product_star_rating: "3.7",
    product_num_ratings: 330,
    product_url: "https://www.amazon.in/dp/B0CDLZBPZ6",
    product_photo:
      "https://m.media-amazon.com/images/I/71US8D64f-L._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹299",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "50+ bought in past month",
    delivery: "FREE Delivery by Amazon",
  },
  {
    asin: "B09TLCVQZ7",
    product_title:
      "Chokhi Bandhni Women&#x27;s Rayon Embroidered Regular Fit Top",
    product_price: "₹349",
    product_original_price: "₹1,249",
    currency: "INR",
    product_star_rating: "3.5",
    product_num_ratings: 1330,
    product_url: "https://www.amazon.in/dp/B09TLCVQZ7",
    product_photo:
      "https://m.media-amazon.com/images/I/61ide6MSf-L._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹349",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: "FREE Delivery by Amazon",
    coupon_text: "Save ₹10 with coupon (limited sizes/colours)",
  },
  {
    asin: "B09YP19ZLZ",
    product_title:
      "SIRIL Women&#x27;s Rayon Mill Printed Regular Regular Fit Top",
    product_price: "₹399",
    product_original_price: "₹1,614",
    currency: "INR",
    product_star_rating: "4.1",
    product_num_ratings: 101,
    product_url: "https://www.amazon.in/dp/B09YP19ZLZ",
    product_photo:
      "https://m.media-amazon.com/images/I/61rtBzZ-2KL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹399",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "50+ bought in past month",
    delivery: "FREE Delivery by Amazon",
    coupon_text: "Save 5% with coupon (limited sizes/colours)",
  },
  {
    asin: "B07FCPL5NX",
    product_title:
      "SWISSTONE Analog Stainless Steel Silver Plated Women&#x27;s Watch (Pink Dial Silver Colored Strap)",
    product_price: "₹299",
    product_original_price: "₹2,599",
    currency: "INR",
    product_star_rating: "4",
    product_num_ratings: 12945,
    product_url: "https://www.amazon.in/dp/B07FCPL5NX",
    product_photo:
      "https://m.media-amazon.com/images/I/817iC5Eq49L._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹299",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "800+ bought in past month",
    delivery: "Get it by Tomorrow, 6 JulyFREE Delivery by Amazon",
  },
  {
    asin: "B0BFYWBVV4",
    product_title:
      "Womens&#x27;s PU Leather hand bags, hand held bag Queen Collection simple and sober (HB-2)",
    product_price: "₹260",
    product_original_price: "₹999",
    currency: "INR",
    product_star_rating: "3.8",
    product_num_ratings: 120,
    product_url: "https://www.amazon.in/dp/B0BFYWBVV4",
    product_photo:
      "https://m.media-amazon.com/images/I/51hEQ83AzrL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹260",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: null,
  },
  {
    asin: "B09PR9D6DF",
    product_title:
      "Wedani Women&#x27;s Casual Puff Sleeves Ruffled Collor Foral Top (Large, Black)",
    product_price: "₹249",
    product_original_price: "₹1,999",
    currency: "INR",
    product_star_rating: "3.3",
    product_num_ratings: 2478,
    product_url: "https://www.amazon.in/dp/B09PR9D6DF",
    product_photo:
      "https://m.media-amazon.com/images/I/71sm8MRnZ2L._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹249",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: "FREE Delivery by Amazon",
  },
  {
    asin: "B0CGNVQN85",
    product_title:
      "Dime Store Engineered Wood Set Top Box Stand TV Stand WiFi Router Rack Wall Shelf for Living Room Stylish Hanging Rack Organizer Shelf Furniture (Brown)",
    product_price: "₹295",
    product_original_price: "₹699",
    currency: "INR",
    product_star_rating: "3.7",
    product_num_ratings: 756,
    product_url: "https://www.amazon.in/dp/B0CGNVQN85",
    product_photo:
      "https://m.media-amazon.com/images/I/71FOJB5UE8L._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 2,
    product_minimum_offer_price: "₹245",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "200+ bought in past month",
    delivery: "Get it by Tomorrow, 6 JulyFREE Delivery by Amazon",
  },
  {
    asin: "B0BLVT4W8D",
    product_title:
      "Techno Buzz Deal Students Lunch Box Sealed Leakage Proof Stainless Steel Lunch Box with Spoon Lid Office Food Container 4 Compartment for School Kids and Adults (Multi Color)",
    product_price: "₹703",
    product_original_price: "₹1,299",
    currency: "INR",
    product_star_rating: "3.9",
    product_num_ratings: 2309,
    product_url: "https://www.amazon.in/dp/B0BLVT4W8D",
    product_photo:
      "https://m.media-amazon.com/images/I/71KiVakNuYL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹703",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: "Get it by Sunday 7 JulyFREE Delivery by Amazon",
  },
  {
    asin: "B01HBQ8SUE",
    product_title:
      "HERSHEY&#x27;S Chocolate Flavored Syrup | Delicious Chocolate Flavor | 200 g Bottle|Liquid",
    product_price: "₹95",
    unit_price: "₹47.50",
    unit_count: 2,
    product_original_price: null,
    currency: "INR",
    product_star_rating: "4.4",
    product_num_ratings: 2811,
    product_url: "https://www.amazon.in/dp/B01HBQ8SUE",
    product_photo:
      "https://m.media-amazon.com/images/I/71S21vuR4EL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 8,
    product_minimum_offer_price: "₹75",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "(₹47.50₹47.50/100 g)",
    delivery: "Get it by Tomorrow, 6 JulyFREE Delivery by Amazon",
  },
  {
    asin: "B07VM6MSBK",
    product_title:
      "Yash Gallery Women&#x27;s Regular Solid Embroidered Straight Regular Fit Tops",
    product_price: "₹418",
    product_original_price: "₹2,399",
    currency: "INR",
    product_star_rating: "3.8",
    product_num_ratings: 1884,
    product_url: "https://www.amazon.in/dp/B07VM6MSBK",
    product_photo:
      "https://m.media-amazon.com/images/I/61YYrjCzksL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹418",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "50+ bought in past month",
    delivery: "FREE Delivery by Amazon",
  },
  {
    asin: "B08HWFWGNX",
    product_title: "Lavie Women&#x27;s Betula Tote Bag | Ladies Purse Handbag",
    product_price: "₹1,049",
    product_original_price: "₹3,190",
    currency: "INR",
    product_star_rating: "4.1",
    product_num_ratings: 22137,
    product_url: "https://www.amazon.in/dp/B08HWFWGNX",
    product_photo:
      "https://m.media-amazon.com/images/I/71FgjWcMjTS._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 4,
    product_minimum_offer_price: "₹998",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "300+ bought in past month",
    delivery: "FREE Delivery by Amazon",
    coupon_text: "Save ₹50 with coupon (limited sizes/colours)",
  },
  {
    asin: "B09XXQF1FT",
    product_title: "DHRUVI TRENDZ Women&#x27;s Regular Fit TOP",
    product_price: "₹299",
    product_original_price: "₹1,999",
    currency: "INR",
    product_star_rating: "3.8",
    product_num_ratings: 7,
    product_url: "https://www.amazon.in/dp/B09XXQF1FT",
    product_photo:
      "https://m.media-amazon.com/images/I/71XER+ReEhL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹299",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: "FREE Delivery by Amazon",
  },
  {
    asin: "B09Z838TRL",
    product_title:
      "ZUVINO Cotton Tops for Women || Formal Tops for Women || Summer Tops for Women || Stylish Top for Women || Plus Size Tops for Women || Floral Tops.",
    product_price: "₹499",
    product_original_price: "₹1,599",
    currency: "INR",
    product_star_rating: "3.8",
    product_num_ratings: 798,
    product_url: "https://www.amazon.in/dp/B09Z838TRL",
    product_photo:
      "https://m.media-amazon.com/images/I/81SaO2GFJRL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹499",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: "FREE Delivery by Amazon",
  },
  {
    asin: "B07MZ4GNGD",
    product_title:
      "Leriya Fashion Women&#x27;s Corduroy Button Down Pocket Shirts Casual Long Sleeve Oversized Blouses Tops | (Medium, Red)",
    product_price: "₹309",
    product_original_price: "₹1,999",
    currency: "INR",
    product_star_rating: "3.5",
    product_num_ratings: 604,
    product_url: "https://www.amazon.in/dp/B07MZ4GNGD",
    product_photo:
      "https://m.media-amazon.com/images/I/61A4bKSgm4L._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹309",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: "FREE Delivery by Amazon",
  },
  {
    asin: "B0BVVXBJNW",
    product_title:
      "Leriya Fashion Top for women || Rayon Floral Printed Shawl Collared Fancy Button Neck || Shirt Style Western Top for Girls || Ideal for Outing || Casual || Summer Wear top for Ladies",
    product_price: "₹299",
    product_original_price: "₹1,999",
    currency: "INR",
    product_star_rating: "3.4",
    product_num_ratings: 46,
    product_url: "https://www.amazon.in/dp/B0BVVXBJNW",
    product_photo:
      "https://m.media-amazon.com/images/I/61aHMNnwElL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹299",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: "FREE Delivery by Amazon",
  },
  {
    asin: "B0BJ95D8Z2",
    product_title: "Selvia Women&#x27;s Top",
    product_price: "₹273",
    product_original_price: "₹1,139",
    currency: "INR",
    product_star_rating: "3.9",
    product_num_ratings: 1162,
    product_url: "https://www.amazon.in/dp/B0BJ95D8Z2",
    product_photo:
      "https://m.media-amazon.com/images/I/51STzgHk8LL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹273",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: "FREE Delivery by Amazon",
  },
  {
    asin: "B0833761VP",
    product_title: "global desi Women&#x27;s Floral Regular Fit Top",
    product_price: "₹325",
    product_original_price: "₹1,299",
    currency: "INR",
    product_star_rating: "3.3",
    product_num_ratings: 37,
    product_url: "https://www.amazon.in/dp/B0833761VP",
    product_photo:
      "https://m.media-amazon.com/images/I/918sYrK+jIL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹325",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: "FREE Delivery by Amazon",
  },
  {
    asin: "B09TVZ3RYT",
    product_title: "Lymio Women Top (526-576)",
    product_price: "₹349",
    product_original_price: "₹1,499",
    currency: "INR",
    product_star_rating: "4",
    product_num_ratings: 4756,
    product_url: "https://www.amazon.in/dp/B09TVZ3RYT",
    product_photo:
      "https://m.media-amazon.com/images/I/61HrmuAz0xL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹349",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "50+ bought in past month",
    delivery: "FREE Delivery by Amazon",
  },
  {
    asin: "B0CTZVGD2P",
    product_title:
      "Leriya Fashion Regular Fit Crop Tops for Women | Solid Ribbed V-Neck Sleeveless Crop Tops for Women| Ribbed Tops for Women",
    product_price: "₹279",
    product_original_price: "₹1,999",
    currency: "INR",
    product_star_rating: "4.5",
    product_num_ratings: 32,
    product_url: "https://www.amazon.in/dp/B0CTZVGD2P",
    product_photo:
      "https://m.media-amazon.com/images/I/71U0pFLoncL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹279",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: "FREE Delivery by Amazon",
  },
  {
    asin: "B09PBXF7YQ",
    product_title:
      "NAINVISH Ethnic Kaftan Co Ord Pant Set | Casual Wear Kaftan Pant &amp; Top Set | Fancy Kaftan Top &amp; Pant Set | | Women Top &amp; Pant",
    product_price: "₹499",
    product_original_price: "₹2,599",
    currency: "INR",
    product_star_rating: "3.5",
    product_num_ratings: 1869,
    product_url: "https://www.amazon.in/dp/B09PBXF7YQ",
    product_photo:
      "https://m.media-amazon.com/images/I/81vu2qtxAvL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹499",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: "FREE Delivery by Amazon",
  },
  {
    asin: "B0BFWVRBFL",
    product_title: "Selvia Women Shirt",
    product_price: "₹332",
    product_original_price: "₹668",
    currency: "INR",
    product_star_rating: "3.6",
    product_num_ratings: 590,
    product_url: "https://www.amazon.in/dp/B0BFWVRBFL",
    product_photo:
      "https://m.media-amazon.com/images/I/41G2WzLIKPL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹332",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: "FREE Delivery by Amazon",
  },
  {
    asin: "B0BZWJXDY7",
    product_title:
      "Sheetal Associates Women&#x27;s Solid Regular Fit Polyester Puff Sleeve Classy Casual Top",
    product_price: "₹279",
    product_original_price: "₹1,999",
    currency: "INR",
    product_star_rating: "3.7",
    product_num_ratings: 180,
    product_url: "https://www.amazon.in/dp/B0BZWJXDY7",
    product_photo:
      "https://m.media-amazon.com/images/I/71VXOpXsgHL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹279",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: "FREE Delivery by Amazon",
  },
  {
    asin: "B0BSTWZBN7",
    product_title: "Harpa Women TOP",
    product_price: "₹614",
    product_original_price: "₹1,499",
    currency: "INR",
    product_star_rating: "2.9",
    product_num_ratings: 17,
    product_url: "https://www.amazon.in/dp/B0BSTWZBN7",
    product_photo:
      "https://m.media-amazon.com/images/I/71WjGY3qc3L._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹614",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: "FREE Delivery by Amazon",
  },
  {
    asin: "B09QL6XFMB",
    product_title:
      "Aahwan Women&#x27;s &amp; Girls&#x27; Solid Ribbed Slim Fit Crop Tank Top",
    product_price: "₹299",
    product_original_price: "₹999",
    currency: "INR",
    product_star_rating: "3.9",
    product_num_ratings: 3496,
    product_url: "https://www.amazon.in/dp/B09QL6XFMB",
    product_photo:
      "https://m.media-amazon.com/images/I/61VhKKAtq3L._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹299",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "100+ bought in past month",
    delivery: "FREE Delivery by Amazon",
  },
];
