/** @format */

const data = {
  status: "OK",
  request_id: "43ff2cb1-f445-4092-8920-6e8bec83af90",
  data: {
    total_products: 9975,
    country: "US",
    domain: "www.amazon.com",
    products: [
      {
        asin: "B0BQ118F2T",
        product_title:
          "Moto G Play 2023 3-Day Battery Unlocked Made for US 3/32GB 16MP Camera Navy Blue",
        product_price: "$99.99",
        product_original_price: "$169.99",
        currency: "USD",
        product_star_rating: "4.1",
        product_num_ratings: 2739,
        product_url: "https://www.amazon.com/dp/B0BQ118F2T",
        product_photo:
          "https://m.media-amazon.com/images/I/61K1Fz5LxvL._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 24,
        product_minimum_offer_price: "$72.06",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: true,
        climate_pledge_friendly: false,
        sales_volume: "3K+ bought in past month",
        delivery:
          "FREE delivery Sat, Jul 6 Or fastest delivery Tomorrow, Jul 2",
      },
      {
        asin: "B0CN1QSH8Q",
        product_title:
          "SAMSUNG Galaxy A15 5G A Series Cell Phone, 128GB Unlocked Android Smartphone, AMOLED Display, Expandable Storage, Knox Security, Super Fast Charging, Hi-Res Camera, US Version, 2024, Blue Black",
        product_price: "$199.99",
        product_original_price: null,
        currency: "USD",
        product_star_rating: "4.1",
        product_num_ratings: 321,
        product_url: "https://www.amazon.com/dp/B0CN1QSH8Q",
        product_photo:
          "https://m.media-amazon.com/images/I/61s0ZzwzSCL._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 29,
        product_minimum_offer_price: "$158.23",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: true,
        climate_pledge_friendly: true,
        sales_volume: "2K+ bought in past month",
        delivery:
          "FREE delivery Sat, Jul 6 Or fastest delivery Tomorrow, Jul 2",
      },
      {
        asin: "B0CRVWXJ6H",
        product_title:
          "Samsung Galaxy A25 5G (SM-A256E/DS), 128GB 6GB RAM, Dual SIM, Factory Unlocked GSM, International Version (Wall Charger Bundle) - (Blue Black)",
        product_price: "$189.95",
        product_original_price: null,
        currency: "USD",
        product_star_rating: "4.1",
        product_num_ratings: 105,
        product_url: "https://www.amazon.com/dp/B0CRVWXJ6H",
        product_photo:
          "https://m.media-amazon.com/images/I/51m744UUjYL._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 20,
        product_minimum_offer_price: "$169.99",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: false,
        climate_pledge_friendly: false,
        sales_volume: "1K+ bought in past month",
        delivery: "FREE delivery Wed, Jul 3 Only 3 left in stock - order soon.",
      },
      {
        asin: "B0CSF1MRRR",
        product_title:
          "BLU G63 | 2023 | 3-Day Battery | Unlocked | 6.8” HD+ Infinity Display | 128/4GB | Dual 13MP Camera | US Version | US Warranty | Green",
        product_price: "$89.99",
        product_original_price: "$129.99",
        currency: "USD",
        product_star_rating: "4",
        product_num_ratings: 33,
        product_url: "https://www.amazon.com/dp/B0CSF1MRRR",
        product_photo:
          "https://m.media-amazon.com/images/I/71EAB02TrzL._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 3,
        product_minimum_offer_price: "$89.97",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: true,
        climate_pledge_friendly: false,
        sales_volume: "500+ bought in past month",
        delivery: "FREE delivery Sat, Jul 6 Or fastest delivery Wed, Jul 3",
      },
      {
        asin: "B0CTD42NJZ",
        product_title:
          "Samsung Galaxy A15 5G (SM-156M/DSN), 256GB 8GB RAM, Dual SIM, Factory Unlocked GSM, International Version (Wall Charger Bundle) (Light Blue)",
        product_price: "$175.89",
        product_original_price: "$189.98",
        currency: "USD",
        product_star_rating: "4.5",
        product_num_ratings: 39,
        product_url: "https://www.amazon.com/dp/B0CTD42NJZ",
        product_photo:
          "https://m.media-amazon.com/images/I/31bNhi6E3eL._AC_UY650_FMwebp_QL65_.jpg",
        product_num_offers: 8,
        product_minimum_offer_price: "$174.95",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: true,
        climate_pledge_friendly: false,
        sales_volume: "500+ bought in past month",
        delivery:
          "FREE delivery Sat, Jul 6 Or fastest delivery Tomorrow, Jul 2",
      },
      {
        asin: "B08VLMQ3KS",
        product_title:
          "Samsung Galaxy S21 5G, US Version, 128GB, Phantom Gray - Unlocked (Renewed)",
        product_price: "$199.99",
        product_original_price: "$379.00",
        currency: "USD",
        product_star_rating: "3.9",
        product_num_ratings: 5743,
        product_url: "https://www.amazon.com/dp/B08VLMQ3KS",
        product_photo:
          "https://m.media-amazon.com/images/I/61jYjeuNUnL._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 102,
        product_minimum_offer_price: "$148.00",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: false,
        climate_pledge_friendly: true,
        sales_volume: "3K+ bought in past month",
        delivery:
          "FREE delivery Wed, Jul 3 Or fastest delivery Tomorrow, Jul 2",
      },
      {
        asin: "B0CTBCDCDH",
        product_title:
          "Samsung Galaxy A05s (SM-A057M/DS), 128GB 4GB RAM, Dual SIM, Factory Unlocked GSM, International Version (Wall Charger Bundle) (Light Violet)",
        product_price: "$135.99",
        product_original_price: null,
        currency: "USD",
        product_star_rating: "4",
        product_num_ratings: 20,
        product_url: "https://www.amazon.com/dp/B0CTBCDCDH",
        product_photo:
          "https://m.media-amazon.com/images/I/21f9A+OzosL._AC_UY365_FMwebp_QL65_.jpg",
        product_num_offers: 8,
        product_minimum_offer_price: "$122.50",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: false,
        climate_pledge_friendly: false,
        sales_volume: "200+ bought in past month",
        delivery: "FREE delivery Wed, Jul 3 Only 2 left in stock - order soon.",
      },
      {
        asin: "B086QB7WZ1",
        product_title:
          "AT&amp;T BL102-2 DECT 6.0 2-Handset Cordless Phone for Home with Answering Machine, Call Blocking, Caller ID Announcer, Audio Assist, Intercom, and Unsurpassed Range, Silver/Black",
        product_price: "$49.45",
        product_original_price: "$56.95",
        currency: "USD",
        product_star_rating: "4.3",
        product_num_ratings: 26338,
        product_url: "https://www.amazon.com/dp/B086QB7WZ1",
        product_photo:
          "https://m.media-amazon.com/images/I/81vjTHTF9WL._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 13,
        product_minimum_offer_price: "$20.91",
        is_best_seller: true,
        is_amazon_choice: false,
        is_prime: true,
        climate_pledge_friendly: false,
        sales_volume: "4K+ bought in past month",
        delivery:
          "FREE delivery Sat, Jul 6 Or fastest delivery Tomorrow, Jul 2",
      },
      {
        asin: "B0CHH6X6H2",
        product_title:
          "Total by Verizon Samsung Galaxy A03s, 32GB, Black - Prepaid Smartphone (Locked)",
        product_price: "$49.88",
        product_original_price: null,
        currency: "USD",
        product_star_rating: "4",
        product_num_ratings: 155,
        product_url: "https://www.amazon.com/dp/B0CHH6X6H2",
        product_photo:
          "https://m.media-amazon.com/images/I/812woqv69CL._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 4,
        product_minimum_offer_price: "$45.00",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: true,
        climate_pledge_friendly: false,
        sales_volume: "500+ bought in past month",
        delivery:
          "FREE delivery Sat, Jul 6 Or fastest delivery Tomorrow, Jul 2",
      },
      {
        asin: "B0CV4NH5T9",
        product_title:
          "SAMSUNG Galaxy A35 5G A Series Cell Phone, 128GB Unlocked Android Smartphone, AMOLED Display, Advanced Triple Camera System, Expandable Storage, Rugged Design, US Version, 2024, Awesome Lilac",
        product_price: "$349.99",
        product_original_price: "$399.99",
        currency: "USD",
        product_star_rating: "4.2",
        product_num_ratings: 47,
        product_url: "https://www.amazon.com/dp/B0CV4NH5T9",
        product_photo:
          "https://m.media-amazon.com/images/I/71lw4ZWUfYL._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 10,
        product_minimum_offer_price: "$335.99",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: true,
        climate_pledge_friendly: false,
        sales_volume: "500+ bought in past month",
        delivery:
          "FREE delivery Sat, Jul 6 Or fastest delivery Tomorrow, Jul 2",
      },
      {
        asin: "B0CCSZZGT7",
        product_title:
          "TracFone Motorola moto g Play, 32GB, Black - Prepaid Smartphone (Locked)",
        product_price: "$47.41",
        product_original_price: "$49.99",
        currency: "USD",
        product_star_rating: "4",
        product_num_ratings: 176,
        product_url: "https://www.amazon.com/dp/B0CCSZZGT7",
        product_photo:
          "https://m.media-amazon.com/images/I/71pGGUaxezL._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$47.41",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: true,
        climate_pledge_friendly: false,
        sales_volume: "1K+ bought in past month",
        delivery:
          "FREE delivery Sat, Jul 6 Or fastest delivery Tomorrow, Jul 2",
      },
      {
        asin: "B096T6Y623",
        product_title:
          "Samsung Galaxy S21 Ultra 5G, US Version, 128GB, Phantom Black - Unlocked (Renewed)",
        product_price: "$298.99",
        product_original_price: null,
        currency: "USD",
        product_star_rating: "4",
        product_num_ratings: 2043,
        product_url: "https://www.amazon.com/dp/B096T6Y623",
        product_photo:
          "https://m.media-amazon.com/images/I/61dlAm9BpqL._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 55,
        product_minimum_offer_price: "$269.00",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: false,
        climate_pledge_friendly: true,
        sales_volume: "2K+ bought in past month",
        delivery: "FREE delivery Jul 2 - 3",
      },
      {
        asin: "B0CHHL5R3H",
        product_title:
          "Total by Verizon TCL 30 Z, 32GB, Black - Prepaid Smartphone (Locked)",
        product_price: "$39.99",
        product_original_price: null,
        currency: "USD",
        product_star_rating: "3.9",
        product_num_ratings: 27,
        product_url: "https://www.amazon.com/dp/B0CHHL5R3H",
        product_photo:
          "https://m.media-amazon.com/images/I/718+xprSIBL._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$39.99",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: true,
        climate_pledge_friendly: false,
        sales_volume: "300+ bought in past month",
        delivery:
          "FREE delivery Sat, Jul 6 Or fastest delivery Tomorrow, Jul 2",
      },
      {
        asin: "B0BLZN9NDG",
        product_title:
          "SAMSUNG,Galaxy A04e (SM-A042M/DS) Dual SIM 32GB,6.5&#x27;&#x27; GSM Unlocked,International Version-Black",
        product_price: "$90.12",
        product_original_price: null,
        currency: "USD",
        product_star_rating: "3.8",
        product_num_ratings: 537,
        product_url: "https://www.amazon.com/dp/B0BLZN9NDG",
        product_photo:
          "https://m.media-amazon.com/images/I/71O2YkTlq-L._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 13,
        product_minimum_offer_price: "$83.88",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: true,
        climate_pledge_friendly: false,
        sales_volume: "500+ bought in past month",
        delivery: "FREE delivery Sat, Jul 6 Or fastest delivery Wed, Jul 3",
      },
      {
        asin: "B092NTYZ78",
        product_title:
          "Panasonic Compact Cordless Phone with DECT 6.0, 1.6&quot; Amber LCD and Illuminated HS Keypad, Call Block, Caller ID, Multiple Display Languages - 1 Handset - KX-TGB810S (Black/Silver)",
        product_price: "$24.99",
        product_original_price: null,
        currency: "USD",
        product_star_rating: "4.2",
        product_num_ratings: 5275,
        product_url: "https://www.amazon.com/dp/B092NTYZ78",
        product_photo:
          "https://m.media-amazon.com/images/I/81k6vcykYYL._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 12,
        product_minimum_offer_price: "$10.49",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: true,
        climate_pledge_friendly: false,
        sales_volume: "1K+ bought in past month",
        delivery:
          "FREE delivery Sat, Jul 6 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jul 2",
      },
      {
        asin: "B00FRSYS12",
        product_title:
          "VTech CS6719-2 2-Handset Expandable Cordless Phone with Caller ID/Call Waiting, Handset Intercom &amp; Backlit Display/Keypad, Silver",
        product_price: "$38.95",
        product_original_price: null,
        currency: "USD",
        product_star_rating: "4.4",
        product_num_ratings: 37306,
        product_url: "https://www.amazon.com/dp/B00FRSYS12",
        product_photo:
          "https://m.media-amazon.com/images/I/71HLNfFVCcL._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 33,
        product_minimum_offer_price: "$20.38",
        is_best_seller: false,
        is_amazon_choice: true,
        is_prime: true,
        climate_pledge_friendly: false,
        sales_volume: "3K+ bought in past month",
        delivery:
          "FREE delivery Sat, Jul 6 Or fastest delivery Tomorrow, Jul 2",
      },
      {
        asin: "B0D5YH5XXG",
        product_title:
          "iPhone 15/15 Pro Max Charger Fast Charging, 20W PD USB C Charger Block with 10FT Long USB C to C Charging Cable Cord for iPhone 15 Pro Max/15Pro/15/15Plus,iPad Pro/Air, Samsung/Android Phone Tablet",
        product_price: "$16.99",
        product_original_price: null,
        currency: "USD",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.com/dp/B0D5YH5XXG",
        product_photo:
          "https://m.media-amazon.com/images/I/51Y33ytIigL._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$16.99",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: false,
        climate_pledge_friendly: false,
        sales_volume: null,
        delivery:
          "FREE delivery on $35 shipped by Amazon.This item will be released on July 27, 2024.",
        coupon_text: "Save 30% with coupon",
      },
      {
        asin: "B0C63FSMWV",
        product_title:
          "SAMSUNG Galaxy Z Flip5 AI Phone, 512GB Unlocked Android Smartphone, Compact, Foldable Design, One-Hand Control, Best Selfies, Full Cover Screen, Hands-Free Use, US Version, 2023, Mint",
        product_price: "$1,119.99",
        product_original_price: null,
        currency: "USD",
        product_star_rating: "4.4",
        product_num_ratings: 351,
        product_url: "https://www.amazon.com/dp/B0C63FSMWV",
        product_photo:
          "https://m.media-amazon.com/images/I/61NKaFRAyRL._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$1,119.99",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: true,
        climate_pledge_friendly: true,
        sales_volume: "100+ bought in past month",
        delivery:
          "FREE delivery Sat, Jul 6 Or fastest delivery Tomorrow, Jul 2",
      },
    ],
  },
};
export default data;
