/** @format */

const data = {
  status: "OK",
  request_id: "43ff2cb1-f445-4092-8920-6e8bec83af90",
  data: {
    total_products: 9975,
    country: "US",
    domain: "www.amazon.com",
    products: [
      {
        asin: "B0BQ118F2T",
        product_title:
          "Moto G Play 2023 3-Day Battery Unlocked Made for US 3/32GB 16MP Camera Navy Blue",
        product_price: "$99.99",
        product_original_price: "$169.99",
        currency: "USD",
        product_star_rating: "4.1",
        product_num_ratings: 2739,
        product_url: "https://www.amazon.com/dp/B0BQ118F2T",
        product_photo:
          "https://m.media-amazon.com/images/I/61K1Fz5LxvL._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 24,
        product_minimum_offer_price: "$72.06",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: true,
        climate_pledge_friendly: false,
        sales_volume: "3K+ bought in past month",
        delivery:
          "FREE delivery Sat, Jul 6 Or fastest delivery Tomorrow, Jul 2",
      },

      {
        asin: "B0CRVWXJ6H",
        product_title:
          "Samsung Galaxy A25 5G (SM-A256E/DS), 128GB 6GB RAM, Dual SIM, Factory Unlocked GSM, International Version (Wall Charger Bundle) - (Blue Black)",
        product_price: "$189.95",
        product_original_price: null,
        currency: "USD",
        product_star_rating: "4.1",
        product_num_ratings: 105,
        product_url: "https://www.amazon.com/dp/B0CRVWXJ6H",
        product_photo:
          "https://m.media-amazon.com/images/I/51m744UUjYL._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 20,
        product_minimum_offer_price: "$169.99",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: false,
        climate_pledge_friendly: false,
        sales_volume: "1K+ bought in past month",
        delivery: "FREE delivery Wed, Jul 3 Only 3 left in stock - order soon.",
      },
      {
        asin: "B0CSF1MRRR",
        product_title:
          "BLU G63 | 2023 | 3-Day Battery | Unlocked | 6.8” HD+ Infinity Display | 128/4GB | Dual 13MP Camera | US Version | US Warranty | Green",
        product_price: "$89.99",
        product_original_price: "$129.99",
        currency: "USD",
        product_star_rating: "4",
        product_num_ratings: 33,
        product_url: "https://www.amazon.com/dp/B0CSF1MRRR",
        product_photo:
          "https://m.media-amazon.com/images/I/71EAB02TrzL._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 3,
        product_minimum_offer_price: "$89.97",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: true,
        climate_pledge_friendly: false,
        sales_volume: "500+ bought in past month",
        delivery: "FREE delivery Sat, Jul 6 Or fastest delivery Wed, Jul 3",
      },
      {
        asin: "B0CTD42NJZ",
        product_title:
          "Samsung Galaxy A15 5G (SM-156M/DSN), 256GB 8GB RAM, Dual SIM, Factory Unlocked GSM, International Version (Wall Charger Bundle) (Light Blue)",
        product_price: "$175.89",
        product_original_price: "$189.98",
        currency: "USD",
        product_star_rating: "4.5",
        product_num_ratings: 39,
        product_url: "https://www.amazon.com/dp/B0CTD42NJZ",
        product_photo:
          "https://m.media-amazon.com/images/I/31bNhi6E3eL._AC_UY650_FMwebp_QL65_.jpg",
        product_num_offers: 8,
        product_minimum_offer_price: "$174.95",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: true,
        climate_pledge_friendly: false,
        sales_volume: "500+ bought in past month",
        delivery:
          "FREE delivery Sat, Jul 6 Or fastest delivery Tomorrow, Jul 2",
      },
      {
        asin: "B08VLMQ3KS",
        product_title:
          "Samsung Galaxy S21 5G, US Version, 128GB, Phantom Gray - Unlocked (Renewed)",
        product_price: "$199.99",
        product_original_price: "$379.00",
        currency: "USD",
        product_star_rating: "3.9",
        product_num_ratings: 5743,
        product_url: "https://www.amazon.com/dp/B08VLMQ3KS",
        product_photo:
          "https://m.media-amazon.com/images/I/61jYjeuNUnL._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 102,
        product_minimum_offer_price: "$148.00",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: false,
        climate_pledge_friendly: true,
        sales_volume: "3K+ bought in past month",
        delivery:
          "FREE delivery Wed, Jul 3 Or fastest delivery Tomorrow, Jul 2",
      },

      {
        asin: "B086QB7WZ1",
        product_title:
          "AT&amp;T BL102-2 DECT 6.0 2-Handset Cordless Phone for Home with Answering Machine, Call Blocking, Caller ID Announcer, Audio Assist, Intercom, and Unsurpassed Range, Silver/Black",
        product_price: "$49.45",
        product_original_price: "$56.95",
        currency: "USD",
        product_star_rating: "4.3",
        product_num_ratings: 26338,
        product_url: "https://www.amazon.com/dp/B086QB7WZ1",
        product_photo:
          "https://m.media-amazon.com/images/I/81vjTHTF9WL._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 13,
        product_minimum_offer_price: "$20.91",
        is_best_seller: true,
        is_amazon_choice: false,
        is_prime: true,
        climate_pledge_friendly: false,
        sales_volume: "4K+ bought in past month",
        delivery:
          "FREE delivery Sat, Jul 6 Or fastest delivery Tomorrow, Jul 2",
      },
      {
        asin: "B0CHH6X6H2",
        product_title:
          "Total by Verizon Samsung Galaxy A03s, 32GB, Black - Prepaid Smartphone (Locked)",
        product_price: "$49.88",
        product_original_price: null,
        currency: "USD",
        product_star_rating: "4",
        product_num_ratings: 155,
        product_url: "https://www.amazon.com/dp/B0CHH6X6H2",
        product_photo:
          "https://m.media-amazon.com/images/I/812woqv69CL._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 4,
        product_minimum_offer_price: "$45.00",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: true,
        climate_pledge_friendly: false,
        sales_volume: "500+ bought in past month",
        delivery:
          "FREE delivery Sat, Jul 6 Or fastest delivery Tomorrow, Jul 2",
      },
      {
        asin: "B0CV4NH5T9",
        product_title:
          "SAMSUNG Galaxy A35 5G A Series Cell Phone, 128GB Unlocked Android Smartphone, AMOLED Display, Advanced Triple Camera System, Expandable Storage, Rugged Design, US Version, 2024, Awesome Lilac",
        product_price: "$349.99",
        product_original_price: "$399.99",
        currency: "USD",
        product_star_rating: "4.2",
        product_num_ratings: 47,
        product_url: "https://www.amazon.com/dp/B0CV4NH5T9",
        product_photo:
          "https://m.media-amazon.com/images/I/71lw4ZWUfYL._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 10,
        product_minimum_offer_price: "$335.99",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: true,
        climate_pledge_friendly: false,
        sales_volume: "500+ bought in past month",
        delivery:
          "FREE delivery Sat, Jul 6 Or fastest delivery Tomorrow, Jul 2",
      },
      {
        asin: "B0CCSZZGT7",
        product_title:
          "TracFone Motorola moto g Play, 32GB, Black - Prepaid Smartphone (Locked)",
        product_price: "$47.41",
        product_original_price: "$49.99",
        currency: "USD",
        product_star_rating: "4",
        product_num_ratings: 176,
        product_url: "https://www.amazon.com/dp/B0CCSZZGT7",
        product_photo:
          "https://m.media-amazon.com/images/I/71pGGUaxezL._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$47.41",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: true,
        climate_pledge_friendly: false,
        sales_volume: "1K+ bought in past month",
        delivery:
          "FREE delivery Sat, Jul 6 Or fastest delivery Tomorrow, Jul 2",
      },
      {
        asin: "B09G9D8KRQ",
        product_title: "Apple iPhone 13 (128GB) - Starlight",
        product_price: "₹51,999",
        product_original_price: "₹59,900",
        currency: "INR",
        product_star_rating: "4.5",
        product_num_ratings: 27849,
        product_url: "https://www.amazon.in/dp/B09G9D8KRQ",
        product_photo:
          "https://m.media-amazon.com/images/I/71GLMJ7TQiL._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "₹51,999",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: true,
        climate_pledge_friendly: false,
        sales_volume: "3K+ bought in past month",
        delivery: "FREE delivery Tue, 9 Jul",
      },
      {
        asin: "B09G9FPGTN",
        product_title: "Apple iPhone 13 (128GB) - Pink",
        product_price: "₹51,999",
        product_original_price: "₹59,900",
        currency: "INR",
        product_star_rating: "4.5",
        product_num_ratings: 27849,
        product_url: "https://www.amazon.in/dp/B09G9FPGTN",
        product_photo:
          "https://m.media-amazon.com/images/I/61l9ppRIiqL._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "₹51,999",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: true,
        climate_pledge_friendly: false,
        sales_volume: "5K+ bought in past month",
        delivery:
          "FREE delivery Mon, 8 Jul Or fastest delivery Tomorrow, 6 Jul",
      },
      {
        asin: "B0CHX1W1XY",
        product_title: "Apple iPhone 15 (128 GB) - Black",
        product_price: "₹71,900",
        product_original_price: "₹79,900",
        currency: "INR",
        product_star_rating: "4.5",
        product_num_ratings: 1780,
        product_url: "https://www.amazon.in/dp/B0CHX1W1XY",
        product_photo:
          "https://m.media-amazon.com/images/I/71657TiFeHL._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "₹71,900",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: true,
        climate_pledge_friendly: false,
        sales_volume: "1K+ bought in past month",
        delivery:
          "FREE delivery Sun, 7 Jul Or fastest delivery Tomorrow, 6 Jul",
      },
      {
        asin: "B09G9BL5CP",
        product_title: "Apple iPhone 13 (128GB) - Blue",
        product_price: "₹51,999",
        product_original_price: "₹59,900",
        currency: "INR",
        product_star_rating: "4.5",
        product_num_ratings: 27849,
        product_url: "https://www.amazon.in/dp/B09G9BL5CP",
        product_photo:
          "https://m.media-amazon.com/images/I/71xb2xkN5qL._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "₹51,999",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: true,
        climate_pledge_friendly: false,
        sales_volume: "4K+ bought in past month",
        delivery:
          "FREE delivery Mon, 8 Jul Or fastest delivery Tomorrow, 6 Jul",
      },
      {
        asin: "B09V4B6K53",
        product_title: "Apple iPhone 13 (128GB) - Green",
        product_price: "₹51,999",
        product_original_price: "₹59,900",
        currency: "INR",
        product_star_rating: "4.5",
        product_num_ratings: 27849,
        product_url: "https://www.amazon.in/dp/B09V4B6K53",
        product_photo:
          "https://m.media-amazon.com/images/I/61-r9zOKBCL._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "₹51,999",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: true,
        climate_pledge_friendly: false,
        sales_volume: "3K+ bought in past month",
        delivery:
          "FREE delivery Sun, 7 Jul Or fastest delivery Tomorrow, 6 Jul",
      },
      {
        asin: "B0BDK62PDX",
        product_title: "Apple iPhone 14 (128 GB) - Blue",
        product_price: "₹62,800",
        product_original_price: "₹79,900",
        currency: "INR",
        product_star_rating: "4.5",
        product_num_ratings: 5316,
        product_url: "https://www.amazon.in/dp/B0BDK62PDX",
        product_photo:
          "https://m.media-amazon.com/images/I/61bK6PMOC3L._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "₹62,800",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: true,
        climate_pledge_friendly: false,
        sales_volume: "200+ bought in past month",
        delivery:
          "FREE delivery Sun, 7 Jul Or fastest delivery Tomorrow, 6 Jul",
      },
      {
        asin: "B0CHXCR9CX",
        product_title: "Apple iPhone 15 Plus (128 GB) - Black",
        product_price: "₹81,999",
        product_original_price: "₹89,900",
        currency: "INR",
        product_star_rating: "4.6",
        product_num_ratings: 837,
        product_url: "https://www.amazon.in/dp/B0CHXCR9CX",
        product_photo:
          "https://m.media-amazon.com/images/I/71zFRCcMS2L._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "₹81,999",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: true,
        climate_pledge_friendly: false,
        sales_volume: "M.R.P: ",
        delivery:
          "FREE delivery Sun, 7 Jul Or fastest delivery Tomorrow, 6 Jul",
      },
      {
        asin: "B09G9HD6PD",
        product_title: "Apple iPhone 13 (128GB) - Midnight",
        product_price: "₹51,999",
        product_original_price: "₹59,900",
        currency: "INR",
        product_star_rating: "4.5",
        product_num_ratings: 27849,
        product_url: "https://www.amazon.in/dp/B09G9HD6PD",
        product_photo:
          "https://m.media-amazon.com/images/I/61VuVU94RnL._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "₹51,999",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: true,
        climate_pledge_friendly: false,
        sales_volume: "2K+ bought in past month",
        delivery: "FREE delivery Tue, 9 Jul Or fastest delivery Sun, 7 Jul",
      },
      {
        asin: "B0CHX6NQMD",
        product_title: "Apple iPhone 15 (128 GB) - Green",
        product_price: null,
        product_original_price: null,
        currency: null,
        product_star_rating: "4.5",
        product_num_ratings: 1780,
        product_url: "https://www.amazon.in/dp/B0CHX6NQMD",
        product_photo:
          "https://m.media-amazon.com/images/I/71nvkHnPpZL._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: null,
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: false,
        climate_pledge_friendly: false,
        sales_volume: null,
        delivery: "Currently unavailable.",
      },
      {
        asin: "B0BDK8LKPJ",
        product_title: "Apple iPhone 14 (128 GB) - Starlight",
        product_price: "₹62,800",
        product_original_price: "₹69,900",
        currency: "INR",
        product_star_rating: "4.5",
        product_num_ratings: 5316,
        product_url: "https://www.amazon.in/dp/B0BDK8LKPJ",
        product_photo:
          "https://m.media-amazon.com/images/I/618Bb+QzCmL._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "₹62,800",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: true,
        climate_pledge_friendly: false,
        sales_volume: "100+ bought in past month",
        delivery:
          "FREE delivery Sun, 7 Jul Or fastest delivery Tomorrow, 6 Jul",
      },
      {
        asin: "B09G9BQS98",
        product_title: "Apple iPhone 13 (256GB) - Midnight",
        product_price: "₹61,490",
        product_original_price: "₹69,900",
        currency: "INR",
        product_star_rating: "4.5",
        product_num_ratings: 27849,
        product_url: "https://www.amazon.in/dp/B09G9BQS98",
        product_photo:
          "https://m.media-amazon.com/images/I/61VuVU94RnL._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "₹61,490",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: true,
        climate_pledge_friendly: false,
        sales_volume: "400+ bought in past month",
        delivery:
          "FREE delivery Mon, 8 Jul Or fastest delivery Tomorrow, 6 Jul",
      },
      {
        asin: "B0CHWV2WYK",
        product_title: "Apple iPhone 15 Pro Max (256 GB) - Black Titanium",
        product_price: "₹1,51,700",
        product_original_price: "₹1,59,900",
        currency: "INR",
        product_star_rating: "4.4",
        product_num_ratings: 306,
        product_url: "https://www.amazon.in/dp/B0CHWV2WYK",
        product_photo:
          "https://m.media-amazon.com/images/I/81Os1SDWpcL._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "₹1,51,700",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: true,
        climate_pledge_friendly: false,
        sales_volume: "100+ bought in past month",
        delivery:
          "FREE delivery Mon, 8 Jul Or fastest delivery Tomorrow, 6 Jul",
      },
      {
        asin: "B09G9BFKZN",
        product_title: "Apple iPhone 13 (256GB) - Starlight",
        product_price: "₹59,900",
        product_original_price: "₹69,900",
        currency: "INR",
        product_star_rating: "4.5",
        product_num_ratings: 27849,
        product_url: "https://www.amazon.in/dp/B09G9BFKZN",
        product_photo:
          "https://m.media-amazon.com/images/I/71GLMJ7TQiL._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "₹59,900",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: false,
        climate_pledge_friendly: false,
        sales_volume: "400+ bought in past month",
        delivery: "FREE delivery",
      },
      {
        asin: "B0CHX6X2WW",
        product_title: "Apple iPhone 15 Plus (128 GB) - Blue",
        product_price: "₹81,999",
        product_original_price: "₹89,900",
        currency: "INR",
        product_star_rating: "4.6",
        product_num_ratings: 837,
        product_url: "https://www.amazon.in/dp/B0CHX6X2WW",
        product_photo:
          "https://m.media-amazon.com/images/I/71PjpS59XLL._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "₹81,999",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: true,
        product_availability: "Only 1 left in stock.",
        climate_pledge_friendly: false,
        sales_volume: "200+ bought in past month",
        delivery: "FREE delivery Mon, 8 Jul Only 1 left in stock.",
      },
      {
        asin: "B0CHX8JCXN",
        product_title: "Apple iPhone 15 (256 GB) - Yellow",
        product_price: "₹82,600",
        product_original_price: "₹89,900",
        currency: "INR",
        product_star_rating: "4.5",
        product_num_ratings: 1780,
        product_url: "https://www.amazon.in/dp/B0CHX8JCXN",
        product_photo:
          "https://m.media-amazon.com/images/I/71REplb5oZL._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "₹82,600",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: true,
        climate_pledge_friendly: false,
        sales_volume: "M.R.P: ",
        delivery:
          "FREE delivery Tue, 9 Jul Or fastest delivery Tomorrow, 6 Jul",
      },
      {
        asin: "B0CHWZCY43",
        product_title: "Apple iPhone 15 Plus (128 GB) - Green",
        product_price: "₹81,999",
        product_original_price: "₹89,900",
        currency: "INR",
        product_star_rating: "4.6",
        product_num_ratings: 837,
        product_url: "https://www.amazon.in/dp/B0CHWZCY43",
        product_photo:
          "https://m.media-amazon.com/images/I/71ZP6U9sWTL._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "₹81,999",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: true,
        climate_pledge_friendly: false,
        sales_volume: "200+ bought in past month",
        delivery:
          "FREE delivery Sun, 7 Jul Or fastest delivery Tomorrow, 6 Jul",
      },
    ],
  },
};
export default data;
